/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-10 10:58:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.amenities;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.dong.DTO.*;

public final class store_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/amenities/../include/head.jsp", Long.valueOf(1708321064000L));
    _jspx_dependants.put("jar:file:/C:/JAVAback/springcamp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springcamping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/amenities/../include/nav.jsp", Long.valueOf(1709794361874L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1705210098272L));
    _jspx_dependants.put("/WEB-INF/views/amenities/../include/footer.jsp", Long.valueOf(1709793907187L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("kr.co.dong.DTO");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>SpringCamping</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/resources/img/favicon.png\">\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS here -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/nice-select.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"css/responsive.css\"> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--[if lte IE 9]>\r\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- header-start -->\r\n");
      out.write("    <header>\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"header-area \">\r\n");
      out.write("         <div id=\"sticky-header\" class=\"main-header-area\">\r\n");
      out.write("            <div class=\"container-fluid p-0\">\r\n");
      out.write("               <div class=\"row align-items-center no-gutters\">\r\n");
      out.write("               \r\n");
      out.write("               <div class=\"col-1\">\r\n");
      out.write("					<div class=\"logo-img\">\r\n");
      out.write("	                   <a href=\"/\">\r\n");
      out.write("	                   <img src=\"../resources/img/main/camping.png\" alt=\"\" style=\"width: 130px; height: 100px; \">\r\n");
      out.write("	                   </a>\r\n");
      out.write("	                </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("               \r\n");
      out.write("	          <div class=\"col-9\" style=\"justify-content: center;\">\r\n");
      out.write("                     <div class=\"main-menu  d-none d-lg-block\">\r\n");
      out.write("                        <nav>\r\n");
      out.write("                           <ul id=\"navigation\">\r\n");
      out.write("                           \r\n");
      out.write("                              <li><a class=\"active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/springcamping/story\">COMPANY\r\n");
      out.write("                            	  <i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                  <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/springcamping/story\">소개글</a></li>\r\n");
      out.write("									<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/springcamping/play\">주변 놀거리</a></li>\r\n");
      out.write("	                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/springcamping/map\">오시는 길</a></li>\r\n");
      out.write("                                 </ul></li>\r\n");
      out.write("                                 \r\n");
      out.write("                              <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/camp/campInfo\">캠핑장안내</a></li>\r\n");
      out.write("                              \r\n");
      out.write("                              <li><a href=\"/rental/rentalAll\">물품대여</a>\r\n");
      out.write("                              \r\n");
      out.write("                              <li><a href=\"/shop/shopAll\">물품판매 <i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                               <ul class=\"submenu\">\r\n");
      out.write("                                                   <li><a href=\"/shop/shopAll\">Shop</a></li>\r\n");
      out.write("                                                   <li><a href=\"/shop/shopNew\">New</a></li>\r\n");
      out.write("                                                   <li><a href=\"/shop/shopBest\">BEST</a></li>\r\n");
      out.write("                                                   <li><a href=\"/shop/shopPromo\">Promotion</a></li>\r\n");
      out.write("                                                   <li><a href=\"/shop/shopLimit\">Limit</a></li>\r\n");
      out.write("                                               </ul>\r\n");
      out.write("                                           </li>\r\n");
      out.write("                                           \r\n");
      out.write("                              <li><a href=\"/amenities/store\">편의시설 <i\r\n");
      out.write("                                    class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                 <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"/amenities/store\">매점</a></li>\r\n");
      out.write("                                    <li><a href=\"/amenities/toiletShowerKitchen\">화장실·샤워실·개수대</a></li>\r\n");
      out.write("                                 </ul></li>\r\n");
      out.write("                                 \r\n");
      out.write("                              <li><a href=\"/board/noticeAll?num=1\">고객센터<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                 <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"../board/boardmain?num=1\">커뮤니티</a></li>\r\n");
      out.write("	                                <li><a href=\"/board/noticeAll?num=1\">공지사항</a></li>\r\n");
      out.write("                                    <li><a href=\"/board/qnalist?num=1\">Q&A</a></li>\r\n");
      out.write("                                 </ul></li>\r\n");
      out.write("                                 \r\n");
      out.write("                       ");
if (request.getSession().getAttribute("user") != null)  {
      out.write("\r\n");
      out.write("                                 \r\n");
      out.write("                              <li><a href=\"../mypage/mypage\">MYPAGE<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                 <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"/mypage/mypage\">MYPAGE</a></li>\r\n");
      out.write("                                    <li><a href=\"/mypage/myResAll\">예약내역</a></li>\r\n");
      out.write("                                    <li><a href=\"/mypage/myBuyAll\">구매내역</a></li>\r\n");
      out.write("                                 </ul>\r\n");
      out.write("                               </li>\r\n");
      out.write("                               \r\n");
      out.write("                        ");
 } 
                           if (request.getSession().getAttribute("user") != null && ((UserDTO) request.getSession().getAttribute("user")).getUser_admin()) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/sales\">Admin<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                 <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/resAdmin\">예약내역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/resOutAdmin\">예약취소내역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/buyAdmin\">구매내역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/buyOutAdmin\">구매취소내역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/sales\">통계</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/userAdmin\">회원관리</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/camp/campAll\">캠핑장관리</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rental/rentalAll\">렌탈물품관리</a></li>\r\n");
      out.write("                                 </ul></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("	               <div class=\"col-2 d-none d-lg-block\">\r\n");
      out.write("                     <div class=\"book_room\">\r\n");
      out.write("								\r\n");
      out.write("                     \r\n");
      out.write("                        <div class=\"socail_links\">\r\n");
      out.write("                           <ul>\r\n");
      out.write("                           	<li>\r\n");
      out.write("                        \r\n");
      out.write("                        ");

								if (request.getSession().getAttribute("user") != null) {
								
      out.write("\r\n");
      out.write("									<a href=\"../book/reservation\">\r\n");
      out.write("										 <i class=\"fa fa-calendar\" style=\"font-size:25px\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("								");

								}else{
								
      out.write("	\r\n");
      out.write("									<a onclick=loginAlert(); class=\"btn-title\">\r\n");
      out.write("										<i class=\"fa fa-calendar\" style=\"font-size:25px\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									<script>\r\n");
      out.write("										function loginAlert(){\r\n");
      out.write("											alert('로그인 후 이용해주세요.');\r\n");
      out.write("										}\r\n");
      out.write("									</script>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        ");

                        if (request.getSession().getAttribute("user") == null) {
                        
      out.write("\r\n");
      out.write("                           <a href=\"../login/login\" class=\"fa fa-user-circle-o\" style=\"font-size:25px\"></a>\r\n");
      out.write("                        ");

                        } else {
                        
      out.write("\r\n");
      out.write("                           <a href=\"/\" class=\"fa fa-user-times\" style=\"font-size:25px\" onclick=\"btnlogout()\"></a>\r\n");
      out.write("                        ");

                        }
                        
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        <a onClick=\"window.open('https://www.instagram.com/mzcamping/')\">\r\n");
      out.write("                              <i class=\"fa fa-instagram\" style=\"font-size:25px\"></i>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                     <div class=\"mobile_menu d-block d-lg-none\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("   </header>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 카카오 로그인 -->\r\n");
      out.write("   <script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("      function btnlogout() {\r\n");
      out.write("         if (confirm(\"로그아웃 하시겠습니까?\")) {\r\n");
      out.write("            location.href = \"/login/logout\";\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- header-end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- bradcam_area_start -->\r\n");
      out.write("    <div class=\"bradcam_area breadcam_bg_1\">\r\n");
      out.write("        <h3> 매점 </h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- bradcam_area_end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    \r\n");
      out.write("    <div class = \"본문\">\r\n");
      out.write("    \r\n");
      out.write("     <img style=\"width: 100%; height: 729px;\" src=\"/resources/img/facilityImg/store/매점1.png\" />\r\n");
      out.write("     <img style=\"width: 100%; height: 729px;\" src=\"/resources/img/facilityImg/store/매점2.png\" />\r\n");
      out.write("     <img style=\"width: 100%; height: 729px;\" src=\"/resources/img/facilityImg/store/매점3.png\" />\r\n");
      out.write("     <img style=\"width: 100%; height: 729px;\" src=\"/resources/img/facilityImg/store/매점4.png\" />\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Main content End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"footer_top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                address\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <p class=\"footer_text\">SpringCamping <br>\r\n");
      out.write("                                KOREA, SUWON</p>\r\n");
      out.write("                            <a href=\"#\" class=\"line-button\">Get Direction</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                Reservation\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <p class=\"footer_text\"> 010-000-0000 <br>\r\n");
      out.write("                                reservation@springcamp.com</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-6 col-lg-2\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                Navigation\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"/springcamping/story\">SpringCamp</a></li>\r\n");
      out.write("                                <li><a href=\"/camp/campInfo\">Camp</a></li>\r\n");
      out.write("                                <li><a href=\"/shop/shopAll\">Shop</a></li>\r\n");
      out.write("                                <li><a href=\"/rental/rentalAll\">Rental</a></li>\r\n");
      out.write("                                <li><a href=\"/amenities/store\">Amenities</a></li>\r\n");
      out.write("                                <li><a href=\"/board/noticeAll?num=1\">Board</a></li>\r\n");
      out.write("                                <li><a href=\"/mypage/mypage\">MYPAGE</a></li>\r\n");
      out.write("                                <li><a href=\"/admin/sales\">Admin</a></li>\r\n");
      out.write("                                \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-6 col-lg-4\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                MADE BY\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            \r\n");
      out.write("                            <p class=\"newsletter_text\">곽 민</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">윤지영</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">성은지</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">차미지</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">박혜연</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">노윤영</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copy-right_text\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"footer_border\"></div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-8 col-md-7 col-lg-9\">\r\n");
      out.write("                        <p class=\"copy_right\">\r\n");
      out.write("                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-5 col-lg-3\">\r\n");
      out.write("                        <div class=\"socail_links\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa fa-instagram\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- form itself end-->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 에약이랑 로그인 버튼인데..... 그건 구현 후 붙일거임! 여기 건들 ㄴㄴ -->\r\n");
      out.write("    \r\n");
      out.write("	<!-- form itself end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JS here -->\r\n");
      out.write("    <script src=\"/resources/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/ajax-form.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/scrollIt.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/gijgo.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--contact js-->\r\n");
      out.write("    <script src=\"/resources/js/contact.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/jquery.form.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/mail-script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/resources/js/main.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
