/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-11 00:45:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.dong.DTO.*;

public final class sales_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/JAVAback/springcamp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springcamping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/admin/../include/nav.jsp", Long.valueOf(1709794361874L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1705210098272L));
    _jspx_dependants.put("/WEB-INF/views/admin/../include/footer.jsp", Long.valueOf(1709793907187L));
    _jspx_dependants.put("/WEB-INF/views/admin/../include/head.jsp", Long.valueOf(1708321064000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("kr.co.dong.DTO");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>SpringCamping</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/resources/img/favicon.png\">\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS here -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/nice-select.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"css/responsive.css\"> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("	    // 날짜 선택기 초기화\r\n");
      out.write("	    $(\"#datepicker\").datepicker({\r\n");
      out.write("	        dateFormat: 'yy-mm-dd',\r\n");
      out.write("	        showOtherMonths: true,\r\n");
      out.write("	        showMonthAfterYear: true,\r\n");
      out.write("	        changeYear: true,\r\n");
      out.write("	        changeMonth: true,\r\n");
      out.write("	        showOn: \"both\",\r\n");
      out.write("	        buttonText: \"선택\",\r\n");
      out.write("	        yearSuffix: \"년\",\r\n");
      out.write("	        monthNamesShort: ['1','2','3','4','5','6','7','8','9','10','11','12'],\r\n");
      out.write("	        monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("	        dayNamesMin: ['일','월','화','수','목','금','토'],\r\n");
      out.write("	        dayNames: ['일요일','월요일','화요일','수요일','목요일','금요일','토요일'],\r\n");
      out.write("	        minDate: \"-1M\",\r\n");
      out.write("	        maxDate: \"+1M\"\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	 // 조회 버튼 클릭 시\r\n");
      out.write("	    $(\"#sales_selectDate\").click(function() {\r\n");
      out.write("	        var start_pay_datetime = $(\"#start_pay_datetime\").val().replace(/-/g, '');\r\n");
      out.write("	        var end_pay_datetime = $(\"#end_pay_datetime\").val().replace(/-/g, '');\r\n");
      out.write("\r\n");
      out.write("	        var data = {\r\n");
      out.write("	            \"start_pay_datetime\": start_pay_datetime,\r\n");
      out.write("	            \"end_pay_datetime\": end_pay_datetime\r\n");
      out.write("	        };\r\n");
      out.write("\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            type: \"POST\",\r\n");
      out.write("	            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/sales\",\r\n");
      out.write("	            data: data,\r\n");
      out.write("	            dataType: 'json',\r\n");
      out.write("	            success: function(response) {\r\n");
      out.write("	                console.log(response);\r\n");
      out.write("	                updateTable(response);\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function(xhr, status, error) {\r\n");
      out.write("	                console.error(xhr.responseText);\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // \"오늘\" 버튼 클릭 시\r\n");
      out.write("	    $(\"button#today\").click(function() {\r\n");
      out.write("	    	setStartDate(0); // 현재 날짜\r\n");
      out.write("	    	setEndDate(0); // 현재 날짜\r\n");
      out.write("	    });\r\n");
      out.write("	    \r\n");
      out.write("	    // \"어제\" 버튼 클릭 시\r\n");
      out.write("	    $(\"button#yesterday\").click(function() {\r\n");
      out.write("	    	setStartDate(-1); // 어제 날짜\r\n");
      out.write("	    	setEndDate(-1); // 어제 날짜\r\n");
      out.write("	    });\r\n");
      out.write("	    \r\n");
      out.write("	 	// \"3일\" 버튼 클릭 시\r\n");
      out.write("	    $(\"#tree_days\").click(function() {\r\n");
      out.write("	    	setStartDate(-3); // 현재 날짜에서 3일 전으로 설정\r\n");
      out.write("	    	setEndDate(0); // 현재 날짜\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // \"7일\" 버튼 클릭 시\r\n");
      out.write("	    $(\"#seven_days\").click(function() {\r\n");
      out.write("	    	setStartDate(-7); // 현재 날짜에서 7일 전으로 설정\r\n");
      out.write("	    	setEndDate(0); // 현재 날짜\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // \"1개월\" 버튼 클릭 시\r\n");
      out.write("	    $(\"#one_month\").click(function() {\r\n");
      out.write("	    	setStartDate(-30); // 현재 날짜에서 1개월 전으로 설정\r\n");
      out.write("	    	setEndDate(0); // 현재 날짜\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // \"3개월\" 버튼 클릭 시\r\n");
      out.write("	    $(\"#tree_month\").click(function() {\r\n");
      out.write("	    	setStartDate(-90); // 현재 날짜에서 3개월 전으로 설정\r\n");
      out.write("	    	setEndDate(0); // 현재 날짜\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // \"6개월\" 버튼 클릭 시\r\n");
      out.write("	    $(\"#six_month\").click(function() {\r\n");
      out.write("	    	setStartDate(-180); // 현재 날짜에서 6개월 전으로 설정\r\n");
      out.write("	    	setEndDate(0); // 현재 날짜\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	 	// 시작날짜 설정 함수\r\n");
      out.write("	    function setStartDate(daysToAdd = 0) {\r\n");
      out.write("	        var date = new Date();\r\n");
      out.write("	        date.setDate(date.getDate() + daysToAdd);\r\n");
      out.write("	        var dd = String(date.getDate()).padStart(2, '0');\r\n");
      out.write("	        var mm = String(date.getMonth() + 1).padStart(2, '0');\r\n");
      out.write("	        var yyyy = date.getFullYear();\r\n");
      out.write("	        var formattedDate = yyyy + '-' + mm + '-' + dd;\r\n");
      out.write("	        $(\"#start_pay_datetime\").val(formattedDate);\r\n");
      out.write("	    }\r\n");
      out.write("	 	\r\n");
      out.write("	 	// 종료날짜 설정 함수\r\n");
      out.write("	    function setEndDate(daysToAdd = 0) {\r\n");
      out.write("	        var date = new Date();\r\n");
      out.write("	        date.setDate(date.getDate() + daysToAdd);\r\n");
      out.write("	        var dd = String(date.getDate()).padStart(2, '0');\r\n");
      out.write("	        var mm = String(date.getMonth() + 1).padStart(2, '0');\r\n");
      out.write("	        var yyyy = date.getFullYear();\r\n");
      out.write("	        var formattedDate = yyyy + '-' + mm + '-' + dd;\r\n");
      out.write("	        $(\"#end_pay_datetime\").val(formattedDate);\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    // 매출 테이블 업데이트 함수\r\n");
      out.write("	    function updateTable(data) {\r\n");
      out.write("	        var tbody = $(\"#sales_table tbody\");\r\n");
      out.write("	        tbody.empty();\r\n");
      out.write("	        $.each(data.salesData, function(index, sale) {\r\n");
      out.write("	            sale.pay_price = sale.pay_price || 0;\r\n");
      out.write("	            sale.pay_ment = sale.pay_ment || '-';\r\n");
      out.write("	            sale.payout_name = sale.payout_name || '-';\r\n");
      out.write("	            sale.payout_price = sale.payout_price || 0;\r\n");
      out.write("	            sale.payout_ment = sale.payout_ment || '-';\r\n");
      out.write("	            sale.payout_date = sale.payout_date || '-';\r\n");
      out.write("	            sale.buy_amount = sale.buy_amount || 0;\r\n");
      out.write("\r\n");
      out.write("	            tbody.append(\r\n");
      out.write("	                \"<tr style='width: 100%; display: flex; justify-content: center; text-align: center;'>\" +\r\n");
      out.write("	                \"<td style='width: 67.6px;'>\" + sale.pay_no + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 83.6px;'>\" + sale.pay_price + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 67.6px;'>\" + sale.pay_ment + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 160px;'>\" + sale.pay_datetime + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 99.6px;'>\" + sale.pay_name + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 99.6px;'>\" + sale.cart_no + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 99.6px;'>\" + sale.rentalres_no + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 131.6px;'>\" + sale.payout_name + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 115.6px;'>\" + sale.payout_price + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 99.6px;'>\" + sale.payout_ment + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 160px;'>\" + sale.payout_date + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 115.6px;'>\" + sale.buy_amount + \"</td>\" +\r\n");
      out.write("	                \"<td style='width: 51.6px;'>\" + (sale.pay_price - sale.payout_price) + \"</td>\" + // 순매출 계산하여 추가\r\n");
      out.write("	                \"</tr>\"\r\n");
      out.write("	            );\r\n");
      out.write("	        });\r\n");
      out.write("	        var tfoot = $(\"#sales_table tfoot\");\r\n");
      out.write("	        tfoot.empty();\r\n");
      out.write("	        var totalPayPrice = data.totalPayPrice || 0;\r\n");
      out.write("	        var totalPayoutPrice = data.totalPayoutPrice || 0;\r\n");
      out.write("	        var netSales = totalPayPrice - totalPayoutPrice;\r\n");
      out.write("	        tfoot.append(\r\n");
      out.write("	            \"<tr style='width: 100%; display: flex; justify-content: center; text-align: center;'>\" +\r\n");
      out.write("	            \"<td style='width: 150.6px;'>결제총금액</td>\" +\r\n");
      out.write("	            \"<td style='width: 67.6px;'>\" + totalPayPrice + \"</td>\" +\r\n");
      out.write("	            \"<td colspan='5' style='width: 458.8px;'></td>\" +\r\n");
      out.write("	            \"<td style='width: 131.6px;'>결제취소총금액</td>\" +\r\n");
      out.write("	            \"<td style='width: 115.6px;'>\" + totalPayoutPrice + \"</td>\" +\r\n");
      out.write("	            \"<td colspan='2' style='width: 259.6px;'></td>\" +\r\n");
      out.write("	            \"<td style='width: 115.6px;'>순매출총금액</td>\" +\r\n");
      out.write("	            \"<td style='width: 51.6px;'>\" + netSales + \"</td>\" +\r\n");
      out.write("	            \"</tr>\"\r\n");
      out.write("	        );\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- header-start -->\r\n");
      out.write("    <header>\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"header-area \">\r\n");
      out.write("         <div id=\"sticky-header\" class=\"main-header-area\">\r\n");
      out.write("            <div class=\"container-fluid p-0\">\r\n");
      out.write("               <div class=\"row align-items-center no-gutters\">\r\n");
      out.write("               \r\n");
      out.write("               <div class=\"col-1\">\r\n");
      out.write("					<div class=\"logo-img\">\r\n");
      out.write("	                   <a href=\"/\">\r\n");
      out.write("	                   <img src=\"../resources/img/main/camping.png\" alt=\"\" style=\"width: 130px; height: 100px; \">\r\n");
      out.write("	                   </a>\r\n");
      out.write("	                </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("               \r\n");
      out.write("	          <div class=\"col-9\" style=\"justify-content: center;\">\r\n");
      out.write("                     <div class=\"main-menu  d-none d-lg-block\">\r\n");
      out.write("                        <nav>\r\n");
      out.write("                           <ul id=\"navigation\">\r\n");
      out.write("                           \r\n");
      out.write("                              <li><a class=\"active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/springcamping/story\">COMPANY\r\n");
      out.write("                            	  <i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                  <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/springcamping/story\">소개글</a></li>\r\n");
      out.write("									<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/springcamping/play\">주변 놀거리</a></li>\r\n");
      out.write("	                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/springcamping/map\">오시는 길</a></li>\r\n");
      out.write("                                 </ul></li>\r\n");
      out.write("                                 \r\n");
      out.write("                              <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/camp/campInfo\">캠핑장안내</a></li>\r\n");
      out.write("                              \r\n");
      out.write("                              <li><a href=\"/rental/rentalAll\">물품대여</a>\r\n");
      out.write("                              \r\n");
      out.write("                              <li><a href=\"/shop/shopAll\">물품판매 <i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                               <ul class=\"submenu\">\r\n");
      out.write("                                                   <li><a href=\"/shop/shopAll\">Shop</a></li>\r\n");
      out.write("                                                   <li><a href=\"/shop/shopNew\">New</a></li>\r\n");
      out.write("                                                   <li><a href=\"/shop/shopBest\">BEST</a></li>\r\n");
      out.write("                                                   <li><a href=\"/shop/shopPromo\">Promotion</a></li>\r\n");
      out.write("                                                   <li><a href=\"/shop/shopLimit\">Limit</a></li>\r\n");
      out.write("                                               </ul>\r\n");
      out.write("                                           </li>\r\n");
      out.write("                                           \r\n");
      out.write("                              <li><a href=\"/amenities/store\">편의시설 <i\r\n");
      out.write("                                    class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                 <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"/amenities/store\">매점</a></li>\r\n");
      out.write("                                    <li><a href=\"/amenities/toiletShowerKitchen\">화장실·샤워실·개수대</a></li>\r\n");
      out.write("                                 </ul></li>\r\n");
      out.write("                                 \r\n");
      out.write("                              <li><a href=\"/board/noticeAll?num=1\">고객센터<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                 <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"../board/boardmain?num=1\">커뮤니티</a></li>\r\n");
      out.write("	                                <li><a href=\"/board/noticeAll?num=1\">공지사항</a></li>\r\n");
      out.write("                                    <li><a href=\"/board/qnalist?num=1\">Q&A</a></li>\r\n");
      out.write("                                 </ul></li>\r\n");
      out.write("                                 \r\n");
      out.write("                       ");
if (request.getSession().getAttribute("user") != null)  {
      out.write("\r\n");
      out.write("                                 \r\n");
      out.write("                              <li><a href=\"../mypage/mypage\">MYPAGE<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                 <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"/mypage/mypage\">MYPAGE</a></li>\r\n");
      out.write("                                    <li><a href=\"/mypage/myResAll\">예약내역</a></li>\r\n");
      out.write("                                    <li><a href=\"/mypage/myBuyAll\">구매내역</a></li>\r\n");
      out.write("                                 </ul>\r\n");
      out.write("                               </li>\r\n");
      out.write("                               \r\n");
      out.write("                        ");
 } 
                           if (request.getSession().getAttribute("user") != null && ((UserDTO) request.getSession().getAttribute("user")).getUser_admin()) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/sales\">Admin<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("                                 <ul class=\"submenu\">\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/resAdmin\">예약내역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/resOutAdmin\">예약취소내역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/buyAdmin\">구매내역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/buyOutAdmin\">구매취소내역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/sales\">통계</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/userAdmin\">회원관리</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/camp/campAll\">캠핑장관리</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rental/rentalAll\">렌탈물품관리</a></li>\r\n");
      out.write("                                 </ul></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("	               <div class=\"col-2 d-none d-lg-block\">\r\n");
      out.write("                     <div class=\"book_room\">\r\n");
      out.write("								\r\n");
      out.write("                     \r\n");
      out.write("                        <div class=\"socail_links\">\r\n");
      out.write("                           <ul>\r\n");
      out.write("                           	<li>\r\n");
      out.write("                        \r\n");
      out.write("                        ");

								if (request.getSession().getAttribute("user") != null) {
								
      out.write("\r\n");
      out.write("									<a href=\"../book/reservation\">\r\n");
      out.write("										 <i class=\"fa fa-calendar\" style=\"font-size:25px\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("								");

								}else{
								
      out.write("	\r\n");
      out.write("									<a onclick=loginAlert(); class=\"btn-title\">\r\n");
      out.write("										<i class=\"fa fa-calendar\" style=\"font-size:25px\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									<script>\r\n");
      out.write("										function loginAlert(){\r\n");
      out.write("											alert('로그인 후 이용해주세요.');\r\n");
      out.write("										}\r\n");
      out.write("									</script>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        ");

                        if (request.getSession().getAttribute("user") == null) {
                        
      out.write("\r\n");
      out.write("                           <a href=\"../login/login\" class=\"fa fa-user-circle-o\" style=\"font-size:25px\"></a>\r\n");
      out.write("                        ");

                        } else {
                        
      out.write("\r\n");
      out.write("                           <a href=\"/\" class=\"fa fa-user-times\" style=\"font-size:25px\" onclick=\"btnlogout()\"></a>\r\n");
      out.write("                        ");

                        }
                        
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        <a onClick=\"window.open('https://www.instagram.com/mzcamping/')\">\r\n");
      out.write("                              <i class=\"fa fa-instagram\" style=\"font-size:25px\"></i>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                     <div class=\"mobile_menu d-block d-lg-none\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("   </header>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 카카오 로그인 -->\r\n");
      out.write("   <script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("      function btnlogout() {\r\n");
      out.write("         if (confirm(\"로그아웃 하시겠습니까?\")) {\r\n");
      out.write("            location.href = \"/login/logout\";\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- header-end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- bradcam_area_start -->\r\n");
      out.write("    <div class=\"bradcam_area breadcam_bg_1\">\r\n");
      out.write("        <h3> 매출통계 </h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- bradcam_area_end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <div class = \"본문\">\r\n");
      out.write("    \r\n");
      out.write("	    <div class=\"sales_btn_cls\" style=\"width: 100%;\">\r\n");
      out.write("		    <table border=\"1\" style=\"width: 100%;\">\r\n");
      out.write("		    <tr style=\"width: 100%; display: flex; justify-content: center;\">\r\n");
      out.write("		    	<th>기간</th>\r\n");
      out.write("			    <td>\r\n");
      out.write("			    	<button id=\"today\">오늘</button>\r\n");
      out.write("				    <button id=\"yesterday\">어제</button>\r\n");
      out.write("				    <button id=\"tree_days\">3일</button>\r\n");
      out.write("				    <button id=\"seven_days\">7일</button>\r\n");
      out.write("				    <button id=\"one_month\">1개월</button>\r\n");
      out.write("				    <button id=\"tree_month\">3개월</button>\r\n");
      out.write("				    <button id=\"six_month\">6개월</button>\r\n");
      out.write("					<input type=\"date\" id=\"start_pay_datetime\" name=\"start_pay_datetime\">\r\n");
      out.write("					<a>~</a>\r\n");
      out.write("					<input type=\"date\" id=\"end_pay_datetime\" name=\"end_pay_datetime\">\r\n");
      out.write("					<button id=\"sales_selectDate\">조회</button>\r\n");
      out.write("			    </td>\r\n");
      out.write("		    </tr>\r\n");
      out.write("			</table>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class=\"sales_details\" style=\"width: 100%;\">\r\n");
      out.write("	        <table id=\"sales_table\" border=\"1\" style=\"width: 100%;\">\r\n");
      out.write("	            <thead>\r\n");
      out.write("	                <tr style=\"width: 100%; display: flex; justify-content: center; text-align: center;\">\r\n");
      out.write("	                    <th>결제번호</th>\r\n");
      out.write("	                    <th>결제총금액</th>\r\n");
      out.write("	                    <th>결제방식</th>\r\n");
      out.write("	                    <th style=\"width: 160px;\">결제일시</th>\r\n");
      out.write("	                    <th>결제상품정보</th>\r\n");
      out.write("	                    <th>장바구니번호</th>\r\n");
      out.write("	                    <th>품목예약번호</th>\r\n");
      out.write("	                    <th>결제취소상품정보</th>\r\n");
      out.write("	                    <th>결제취소총금액</th>\r\n");
      out.write("	                    <th>결제취소방식</th>\r\n");
      out.write("	                    <th style=\"width: 160px;\">결제취소일시</th>\r\n");
      out.write("	                    <th>쇼핑몰구매수량</th>\r\n");
      out.write("	                    <th>순매출</th>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	            </thead>\r\n");
      out.write("	            <tbody>\r\n");
      out.write("	            </tbody>\r\n");
      out.write("	            <tfoot id=\"sales_table tfoot\"></tfoot>\r\n");
      out.write("	        </table>\r\n");
      out.write("	     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Main content End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"footer_top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                address\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <p class=\"footer_text\">SpringCamping <br>\r\n");
      out.write("                                KOREA, SUWON</p>\r\n");
      out.write("                            <a href=\"#\" class=\"line-button\">Get Direction</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                Reservation\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <p class=\"footer_text\"> 010-000-0000 <br>\r\n");
      out.write("                                reservation@springcamp.com</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-6 col-lg-2\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                Navigation\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"/springcamping/story\">SpringCamp</a></li>\r\n");
      out.write("                                <li><a href=\"/camp/campInfo\">Camp</a></li>\r\n");
      out.write("                                <li><a href=\"/shop/shopAll\">Shop</a></li>\r\n");
      out.write("                                <li><a href=\"/rental/rentalAll\">Rental</a></li>\r\n");
      out.write("                                <li><a href=\"/amenities/store\">Amenities</a></li>\r\n");
      out.write("                                <li><a href=\"/board/noticeAll?num=1\">Board</a></li>\r\n");
      out.write("                                <li><a href=\"/mypage/mypage\">MYPAGE</a></li>\r\n");
      out.write("                                <li><a href=\"/admin/sales\">Admin</a></li>\r\n");
      out.write("                                \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-6 col-lg-4\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                MADE BY\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            \r\n");
      out.write("                            <p class=\"newsletter_text\">곽 민</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">윤지영</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">성은지</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">차미지</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">박혜연</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">노윤영</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copy-right_text\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"footer_border\"></div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-8 col-md-7 col-lg-9\">\r\n");
      out.write("                        <p class=\"copy_right\">\r\n");
      out.write("                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-5 col-lg-3\">\r\n");
      out.write("                        <div class=\"socail_links\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa fa-instagram\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- form itself end-->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 에약이랑 로그인 버튼인데..... 그건 구현 후 붙일거임! 여기 건들 ㄴㄴ -->\r\n");
      out.write("    \r\n");
      out.write("	<!-- form itself end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
