/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-11 00:45:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/login/../include/head.jsp", Long.valueOf(1708321064000L));
    _jspx_dependants.put("jar:file:/C:/JAVAback/springcamp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springcamping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/login/../include/footer.jsp", Long.valueOf(1709793907187L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1705210098272L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>SpringCamping</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/resources/img/favicon.png\">\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS here -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/nice-select.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"css/responsive.css\"> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/login.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!--[if lte IE 9]>\r\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- features_room_startt -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-xl-12\">\r\n");
      out.write("		<div class=\"section_title text-center mb-100\">\r\n");
      out.write("			<a href=\"/\"><img src=\"/resources/img/캠핑로고2.png\" alt=\"\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- features_room_end -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Links -->\r\n");
      out.write("		<ul class=\"links\">\r\n");
      out.write("			<li><a id=\"signin\">로그인</a></li>\r\n");
      out.write("			<li><a href=\"signup\">회원가입</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("		<!-- Form -->\r\n");
      out.write("		<form method=\"post\">\r\n");
      out.write("			<!-- email input -->\r\n");
      out.write("			<div class=\"first-input input__block first-input__block\">\r\n");
      out.write("				<input type=\"email\" placeholder=\"이메일\" class=\"input\" id=\"user_id\"\r\n");
      out.write("					name=\"user_id\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- password input -->\r\n");
      out.write("			<div class=\"input__block\">\r\n");
      out.write("				<input type=\"password\" placeholder=\"비밀번호\" class=\"input\"\r\n");
      out.write("					id=\"user_password\" name=\"user_password\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- sign in button -->\r\n");
      out.write("			<button type=\"button\" class=\"signin__btn\" onclick=\"btnEmaillogin()\">로그인</button>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- separator -->\r\n");
      out.write("		<div class=\"separator\">\r\n");
      out.write("			<p>OR</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- google button -->\r\n");
      out.write("		\r\n");
      out.write("		<button class=\"github__btn\" style=\"height: unset;\">\r\n");
      out.write("			<a id=\"kakao-login-btn\" href=\"javascript:loginWithKakao()\">\r\n");
      out.write("  				<img src=\"https://k.kakaocdn.net/14/dn/btroDszwNrM/I6efHub1SN5KCJqLm1Ovx1/o.jpg\" width=\"222\"\r\n");
      out.write("    	 			 alt=\"카카오 로그인 버튼\" />\r\n");
      out.write("			</a>\r\n");
      out.write("		</button>\r\n");
      out.write("		\r\n");
      out.write("<!--  \r\n");
      out.write("		<footer>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"idFind\">로그인 정보를 잊으셨나요?</a>\r\n");
      out.write("			</p>\r\n");
      out.write("\r\n");
      out.write("		</footer>\r\n");
      out.write("		-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"footer_top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                address\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <p class=\"footer_text\">SpringCamping <br>\r\n");
      out.write("                                KOREA, SUWON</p>\r\n");
      out.write("                            <a href=\"#\" class=\"line-button\">Get Direction</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-md-6 col-lg-3\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                Reservation\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <p class=\"footer_text\"> 010-000-0000 <br>\r\n");
      out.write("                                reservation@springcamp.com</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-6 col-lg-2\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                Navigation\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"/springcamping/story\">SpringCamp</a></li>\r\n");
      out.write("                                <li><a href=\"/camp/campInfo\">Camp</a></li>\r\n");
      out.write("                                <li><a href=\"/shop/shopAll\">Shop</a></li>\r\n");
      out.write("                                <li><a href=\"/rental/rentalAll\">Rental</a></li>\r\n");
      out.write("                                <li><a href=\"/amenities/store\">Amenities</a></li>\r\n");
      out.write("                                <li><a href=\"/board/noticeAll?num=1\">Board</a></li>\r\n");
      out.write("                                <li><a href=\"/mypage/mypage\">MYPAGE</a></li>\r\n");
      out.write("                                <li><a href=\"/admin/sales\">Admin</a></li>\r\n");
      out.write("                                \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-6 col-lg-4\">\r\n");
      out.write("                        <div class=\"footer_widget\">\r\n");
      out.write("                            <h3 class=\"footer_title\">\r\n");
      out.write("                                MADE BY\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            \r\n");
      out.write("                            <p class=\"newsletter_text\">곽 민</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">윤지영</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">성은지</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">차미지</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">박혜연</p>\r\n");
      out.write("                            <p class=\"newsletter_text\">노윤영</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copy-right_text\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"footer_border\"></div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-8 col-md-7 col-lg-9\">\r\n");
      out.write("                        <p class=\"copy_right\">\r\n");
      out.write("                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-5 col-lg-3\">\r\n");
      out.write("                        <div class=\"socail_links\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa fa-instagram\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- link that opens popup -->\r\n");
      out.write("\r\n");
      out.write("	<!--contact js-->\r\n");
      out.write("	<script src=\"/resources/js/contact.js\"></script>\r\n");
      out.write("	<script src=\"/resources/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"/resources/js/jquery.form.js\"></script>\r\n");
      out.write("	<script src=\"/resources/js/jquery.validate.min.js\"></script>\r\n");
      out.write("	<script src=\"/resources/js/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 카카오 로그인 -->\r\n");
      out.write("	<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		const KaApiKey = \"81846d077282b604a3ee324e8089b47d\";\r\n");
      out.write("	      //2. 카카오 초기화\r\n");
      out.write("	      Kakao.init(KaApiKey);\r\n");
      out.write("	      Kakao.isInitialized();\r\n");
      out.write("	      //3. 카카오로그인 코드 확인\r\n");
      out.write("	      function loginWithKakao() {\r\n");
      out.write("	        Kakao.Auth.login({\r\n");
      out.write("	          success: function (authObj) {\r\n");
      out.write("	            console.log(authObj); //access토큰 값\r\n");
      out.write("	            Kakao.Auth.setAccessToken(authObj.access_token); //access 토큰 값 저장\r\n");
      out.write("	            getInfo();\r\n");
      out.write("	          },\r\n");
      out.write("	          fail: function (err) {\r\n");
      out.write("	            console.log(err);\r\n");
      out.write("	          },\r\n");
      out.write("	        });\r\n");
      out.write("	      }\r\n");
      out.write("	      //4. 엑세스 토큰을 발급받고, 아래 함수를 호출시켜 사용자 정보 받아옴.\r\n");
      out.write("	      function getInfo() {\r\n");
      out.write("	        Kakao.API.request({\r\n");
      out.write("	          url: \"/v2/user/me\",\r\n");
      out.write("	          success: function (res) {\r\n");
      out.write("	            console.log(res);\r\n");
      out.write("	            var kakaoId = res.id;\r\n");
      out.write("	            // KAKAO id 획득\r\n");
      out.write("	            \r\n");
      out.write("	            const data = {\r\n");
      out.write("	            	\"user_id\": kakaoId,\r\n");
      out.write("	            	\"user_intype\" : \"kakao\"\r\n");
      out.write("	            }\r\n");
      out.write("	            $.ajax({\r\n");
      out.write("						type : 'post',\r\n");
      out.write("						url : '/login/kakao',\r\n");
      out.write("						data : data,\r\n");
      out.write("						async : true,\r\n");
      out.write("						contentType : 'application/x-www-form-urlencoded;charset=UTF-8',\r\n");
      out.write("						success : function(result) {\r\n");
      out.write("							location.href = \"/\";\r\n");
      out.write("						},\r\n");
      out.write("						error : function() {\r\n");
      out.write("							alert('error');\r\n");
      out.write("						}\r\n");
      out.write("					})\r\n");
      out.write("	          },\r\n");
      out.write("	          fail: function (error) {\r\n");
      out.write("	            alert(\"카카오 로그인 실패\" + JSON.stringify(error));\r\n");
      out.write("	          },\r\n");
      out.write("	        });\r\n");
      out.write("	      }\r\n");
      out.write("	\r\n");
      out.write("		function btnEmaillogin() {\r\n");
      out.write("			if ($(\"#user_id\").val() == \"\") {\r\n");
      out.write("				alert(\"이메일을 입력하세요.\")\r\n");
      out.write("				$(\"#user_id\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if ($(\"#user_password\").val() == \"\") {\r\n");
      out.write("				alert(\"패스워드를 입력하세요.\");\r\n");
      out.write("				$(\"#user_password\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var data = {\r\n");
      out.write("				'user_id' : $(\"#user_id\").val(),\r\n");
      out.write("				'user_password' : $(\"#user_password\").val()\r\n");
      out.write("			}\r\n");
      out.write("			$.ajax({\r\n");
      out.write("						type : 'post',\r\n");
      out.write("						url : '/login/login',\r\n");
      out.write("						data : data,\r\n");
      out.write("						async : true,\r\n");
      out.write("						contentType : 'application/x-www-form-urlencoded;charset=UTF-8',\r\n");
      out.write("						success : function(result) {\r\n");
      out.write("							if (result && result.login) {\r\n");
      out.write("								location.href = \"/\";\r\n");
      out.write("							} else {\r\n");
      out.write("								alert('이메일 또는 패스워드가 틀립니다.');\r\n");
      out.write("							}\r\n");
      out.write("						},\r\n");
      out.write("						error : function() {\r\n");
      out.write("							alert('error');\r\n");
      out.write("						}\r\n");
      out.write("					})\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
