/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-10 10:57:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class popup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/JAVAback/springcamp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springcamping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1705210098272L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- style -->\r\n");
      out.write("<style>\r\n");
      out.write("font-family: SF Pro KR, SF Pro Display, SF Pro Icons, AOS Icons, Apple Gothic, HY Gulim, MalgunGothic, HY Dotum, Lexi Gulim, Helvetica Neue, Helvetica, Arial, sans-serif;\r\n");
      out.write(".layerPopup img{margin-bottom : 20px;}\r\n");
      out.write(".layerPopup:before {display:block; content:\"\"; position:fixed; left:0; top:0; width:100%; height:100%; background:rgba(0,0,0,.5); z-index:9000}\r\n");
      out.write(".layerPopup .layerBox {z-index:10000;   \r\n");
      out.write("position:fixed; left:50%; top:50%; transform:translate(-50%, -50%); padding:30px; background:#fff; border-radius:6px; }\r\n");
      out.write(".layerPopup .layerBox .title {margin-bottom:10px; padding-bottom:10px; font-weight:600; border-bottom:1px solid #d9d9d9;}\r\n");
      out.write(".layerPopup .layerBox .btnTodayHide {\r\n");
      out.write("font-size:14px; font-weight:600; color:black; \r\n");
      out.write("float: left; text-decoration:none; width: 150px; \r\n");
      out.write("height : 30px; line-height:30px;border:black solid 1px; text-align : center;text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write(".layerPopup div{\r\n");
      out.write("	display : inline;\r\n");
      out.write("}\r\n");
      out.write(".layerPopup form{\r\n");
      out.write("	margin-top : 5px;\r\n");
      out.write("	font-size:16px; font-weight:600;\r\n");
      out.write("	weight: 100%;\r\n");
      out.write("	height : 30px;\r\n");
      out.write("	line-height:30px\r\n");
      out.write("}\r\n");
      out.write(".layerPopup #close {\r\n");
      out.write("font-size:16px; font-weight:600; width: 40px; height : 30px;color:black; float: right; line-height:30px; text-align : center;text-decoration:underline;\r\n");
      out.write("}\r\n");
      out.write(".layerPopup a{\r\n");
      out.write("	text-decoration : none;\r\n");
      out.write("	color : black; width: 50px;height : 40px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- layer popup content -->\r\n");
      out.write("<div class=\"layerPopup\" id=\"layer_popup\" style=\"visibility: visible;\">\r\n");
      out.write("    <div class=\"layerBox\">\r\n");
      out.write("        <h4 class=\"title\" style=\"text-align: center;\">♥방문을 환영합니다♥</h4>\r\n");
      out.write("        <div class=\"cont\">\r\n");
      out.write("           <p> \r\n");
      out.write("            <img src=\"../resources/img/main/popup.png\" width=350 height=500 usemap=\"#popup\" alt=\"event page\">\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("          <form name=\"pop_form\">\r\n");
      out.write("        <div id=\"check\" ><input type=\"checkbox\" name=\"chkbox\" value=\"checkbox\" id='chkbox' >\r\n");
      out.write("        <label for=\"chkbox\">&nbsp&nbsp오늘 하루동안 보지 않기</label></div>\r\n");
      out.write("		<div id=\"close\"><a href=\"javascript:closePop();\">닫기</a></div>    \r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("//head 태그 안에 스크립트 선언\r\n");
      out.write("        function setCookie( name, value, expiredays ) {\r\n");
      out.write("            var todayDate = new Date();\r\n");
      out.write("            todayDate.setDate( todayDate.getDate() + expiredays ); \r\n");
      out.write("            document.cookie = name + \"=\" + escape( value ) + \"; path=/; expires=\" + todayDate.toGMTString() + \";\"\r\n");
      out.write("        }\r\n");
      out.write("        function closePop() {\r\n");
      out.write("            if ( document.pop_form.chkbox.checked ){\r\n");
      out.write("                setCookie( \"maindiv\", \"done\" , 1 );\r\n");
      out.write("            }\r\n");
      out.write("            document.all['layer_popup'].style.visibility = \"hidden\";\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write(" <script language=\"Javascript\">\r\n");
      out.write("    cookiedata = document.cookie;   \r\n");
      out.write("    if ( cookiedata.indexOf(\"maindiv=done\") < 0 ){     \r\n");
      out.write("        document.all['layer_popup'].style.visibility = \"visible\";\r\n");
      out.write("    }\r\n");
      out.write("    else {\r\n");
      out.write("        document.all['layer_popup'].style.visibility = \"hidden\";\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
